FROM python:3.10-slim-buster

COPY src src
COPY tests tests
COPY waiters tests/waiters

WORKDIR tests

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["pytest"]
